spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "Hola"
  default-value: "Mundo (by Joel)"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
